/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllNotifications"];
        put: operations["updateNotification"];
        post: operations["createNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory-transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put: operations["update_1"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllIngredientCategory"];
        put: operations["updateIngredientCategory"];
        post: operations["createIngredientCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dish-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_1"];
        put: operations["update_2"];
        post: operations["save_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_2"];
        put: operations["update_3"];
        post: operations["save_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_3"];
        put: operations["update_4"];
        post: operations["save_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_4"];
        put?: never;
        post: operations["save_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sài chung cho create & update, nếu update thì gửi id, còn create thì ko cần
         * @description Tạo món ăn mới kèm nguyên liệu và thông tin chi tiết, gửi kèm 1 map chứa Id Ingredient và số lượng. Account chỉ cần gửi Id, mấy field khác để trống
         */
        post: operations["save_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dish-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_5"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markAsRead"];
        trace?: never;
    };
    "/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["demo"];
        put?: never;
        post?: never;
        delete: operations["deleteRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forgotPassword"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/vnpay-return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handleVnPayReturn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/testpayment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["testPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment/momo-return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handleMomoReturn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationById"];
        put?: never;
        post?: never;
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/account/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationByAccountId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sendMail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_2"];
        put?: never;
        post?: never;
        delete: operations["deleteIngredientCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dish-templates/{sizeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findBySizeCode"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dish-category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_3"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discount/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_4"];
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById_5"];
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** Format: int32 */
            id?: number;
            name: string;
            /** @enum {string} */
            role: "ADMIN" | "STAFF" | "USER";
            /** Format: date-time */
            createAt?: string;
            /** Format: date-time */
            updateAt?: string;
            password?: string;
            mail: string;
            phone?: string;
            active?: boolean;
        };
        Notification: {
            /** Format: int32 */
            id?: number;
            title?: string;
            message?: string;
            /** Format: date-time */
            createdAt?: string;
            account?: components["schemas"]["Account"];
            read?: boolean;
        };
        Ingredient: {
            /** Format: int32 */
            id?: number;
            name: string;
            category?: components["schemas"]["IngredientCategory"];
            /** @enum {string} */
            unit?: "GRAM" | "KILOGRAM" | "LITER" | "PCS";
            active?: boolean;
            imgUrl?: string;
            publicId?: string;
        };
        IngredientCategory: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
        };
        InventoryTransaction: {
            /** Format: int32 */
            id?: number;
            ingredient?: components["schemas"]["Ingredient"];
            orders?: components["schemas"]["Orders"];
            /** Format: date-time */
            createAt?: string;
            /** Format: int32 */
            quantity?: number;
            transactionType: boolean;
        };
        Orders: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createAt?: string;
            /** Format: int32 */
            totalPrice?: number;
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED" | "CONFIRMED" | "CANCELLED";
            /** Format: int32 */
            userId?: number;
            /** Format: int32 */
            staffId?: number;
            note?: string;
            /** Format: int32 */
            ranking?: number;
            /** Format: int32 */
            comment?: number;
        };
        IngredientUpdateRequest: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            categoryId?: number;
            /** @enum {string} */
            unit?: "GRAM" | "KILOGRAM" | "LITER" | "PCS";
            active?: boolean;
            /** Format: binary */
            file?: string;
        };
        DishCategoryUpdateRequest: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string;
        };
        DishCategory: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
        };
        DiscountUpdateRequest: {
            /** Format: int32 */
            id: number;
            name?: string;
            /** Format: int32 */
            discountPercent?: number;
            /** Format: int32 */
            quantity?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            description?: string;
        };
        Discount: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: int32 */
            discountPercent?: number;
            /** Format: int32 */
            quantity?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            code?: string;
            description?: string;
        };
        AccountUpdateRequest: {
            /** Format: int32 */
            id: number;
            name: string;
            /** @enum {string} */
            role?: "ADMIN" | "STAFF" | "USER";
            mail: string;
            active?: boolean;
        };
        MakeOrderRequest: {
            /** Format: int32 */
            accountId?: number;
            paymentMethod?: string;
            note?: string;
            items?: components["schemas"]["OrderItemDTO"][];
        };
        OrderItemDTO: {
            /** Format: int32 */
            dishId?: number;
            /** Format: int32 */
            basedOnId?: number;
            name?: string;
            /** Format: int32 */
            quantity?: number;
            recipe?: components["schemas"]["RecipeItemDTO"][];
        };
        RecipeItemDTO: {
            /** Format: int32 */
            ingredientId?: number;
            /** Format: int32 */
            quantity?: number;
            /** @enum {string} */
            sourceType?: "BASE" | "ADDON" | "REMOVED";
        };
        IngredientCreateRequest: {
            name: string;
            /** Format: int32 */
            categoryId: number;
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "LITER" | "PCS";
            /** Format: binary */
            file?: string;
        };
        DishCreateRequest: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
            /** Format: int32 */
            price?: number;
            imageUrl?: string;
            account: components["schemas"]["Account"];
            /** @enum {string} */
            dishType: "PRESET" | "CUSTOM";
            ingredients: {
                [key: string]: number;
            };
            public?: boolean;
            active?: boolean;
        };
        Dish: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            price?: number;
            imageUrl?: string;
            account?: components["schemas"]["Account"];
            /** @enum {string} */
            dishType?: "PRESET" | "CUSTOM";
            /** Format: int32 */
            usedQuantity?: number;
            public?: boolean;
            active?: boolean;
        };
        DishTemplate: {
            /** @enum {string} */
            size?: "S" | "M" | "L";
            name?: string;
            /** Format: double */
            priceRatio?: number;
            /** Format: double */
            quantityRatio?: number;
            /** Format: int32 */
            max_Carb?: number;
            /** Format: int32 */
            max_Protein?: number;
            /** Format: int32 */
            max_Vegetable?: number;
        };
        DishCategoryCreateRequest: {
            name: string;
            description?: string;
        };
        DiscountCreateRequest: {
            name: string;
            /** Format: int32 */
            discountPercent?: number;
            /** Format: int32 */
            quantity?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            code?: string;
            description?: string;
        };
        AccountCreateRequest: {
            name: string;
            mail: string;
            /** @enum {string} */
            role: "ADMIN" | "STAFF" | "USER";
            password: string;
        };
        UserDTO: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: int32 */
            age?: number;
        };
        WarpResponseUserDTO: {
            /** Format: int32 */
            statusCode?: number;
            message?: string;
            data?: components["schemas"]["UserDTO"];
        };
        ApplicationContext: {
            parent?: unknown;
            id?: string;
            displayName?: string;
            applicationName?: string;
            /** Format: int64 */
            startupDate?: number;
            autowireCapableBeanFactory?: components["schemas"]["AutowireCapableBeanFactory"];
            environment?: components["schemas"]["Environment"];
            /** Format: int32 */
            beanDefinitionCount?: number;
            beanDefinitionNames?: string[];
            parentBeanFactory?: components["schemas"]["BeanFactory"];
            classLoader?: {
                name?: string;
                registeredAsParallelCapable?: boolean;
                parent?: {
                    name?: string;
                    registeredAsParallelCapable?: boolean;
                    unnamedModule?: {
                        name?: string;
                        classLoader?: {
                            name?: string;
                            registeredAsParallelCapable?: boolean;
                            definedPackages?: {
                                name?: string;
                                annotations?: unknown[];
                                declaredAnnotations?: unknown[];
                                sealed?: boolean;
                                specificationTitle?: string;
                                specificationVersion?: string;
                                specificationVendor?: string;
                                implementationTitle?: string;
                                implementationVersion?: string;
                                implementationVendor?: string;
                            }[];
                            defaultAssertionStatus?: boolean;
                        };
                        descriptor?: {
                            open?: boolean;
                            automatic?: boolean;
                        };
                        named?: boolean;
                        annotations?: unknown[];
                        declaredAnnotations?: unknown[];
                        packages?: string[];
                        layer?: unknown;
                    };
                    definedPackages?: {
                        name?: string;
                        annotations?: unknown[];
                        declaredAnnotations?: unknown[];
                        sealed?: boolean;
                        specificationTitle?: string;
                        specificationVersion?: string;
                        specificationVendor?: string;
                        implementationTitle?: string;
                        implementationVersion?: string;
                        implementationVendor?: string;
                    }[];
                    defaultAssertionStatus?: boolean;
                };
                unnamedModule?: {
                    name?: string;
                    classLoader?: {
                        name?: string;
                        registeredAsParallelCapable?: boolean;
                        definedPackages?: {
                            name?: string;
                            annotations?: unknown[];
                            declaredAnnotations?: unknown[];
                            sealed?: boolean;
                            specificationTitle?: string;
                            specificationVersion?: string;
                            specificationVendor?: string;
                            implementationTitle?: string;
                            implementationVersion?: string;
                            implementationVendor?: string;
                        }[];
                        defaultAssertionStatus?: boolean;
                    };
                    descriptor?: {
                        open?: boolean;
                        automatic?: boolean;
                    };
                    named?: boolean;
                    annotations?: unknown[];
                    declaredAnnotations?: unknown[];
                    packages?: string[];
                    layer?: unknown;
                };
                definedPackages?: {
                    name?: string;
                    annotations?: unknown[];
                    declaredAnnotations?: unknown[];
                    sealed?: boolean;
                    specificationTitle?: string;
                    specificationVersion?: string;
                    specificationVendor?: string;
                    implementationTitle?: string;
                    implementationVersion?: string;
                    implementationVendor?: string;
                }[];
                defaultAssertionStatus?: boolean;
            };
        };
        AutowireCapableBeanFactory: unknown;
        BeanFactory: unknown;
        DefaultHttpStatusCode: components["schemas"]["HttpStatusCode"];
        Environment: {
            activeProfiles?: string[];
            defaultProfiles?: string[];
        };
        FilterRegistration: {
            servletNameMappings?: string[];
            urlPatternMappings?: string[];
            name?: string;
            className?: string;
            initParameters?: {
                [key: string]: string;
            };
        };
        /** @enum {unknown} */
        HttpStatus: "100 CONTINUE" | "101 SWITCHING_PROTOCOLS" | "102 PROCESSING" | "103 EARLY_HINTS" | "103 CHECKPOINT" | "200 OK" | "201 CREATED" | "202 ACCEPTED" | "203 NON_AUTHORITATIVE_INFORMATION" | "204 NO_CONTENT" | "205 RESET_CONTENT" | "206 PARTIAL_CONTENT" | "207 MULTI_STATUS" | "208 ALREADY_REPORTED" | "226 IM_USED" | "300 MULTIPLE_CHOICES" | "301 MOVED_PERMANENTLY" | "302 FOUND" | "302 MOVED_TEMPORARILY" | "303 SEE_OTHER" | "304 NOT_MODIFIED" | "305 USE_PROXY" | "307 TEMPORARY_REDIRECT" | "308 PERMANENT_REDIRECT" | "400 BAD_REQUEST" | "401 UNAUTHORIZED" | "402 PAYMENT_REQUIRED" | "403 FORBIDDEN" | "404 NOT_FOUND" | "405 METHOD_NOT_ALLOWED" | "406 NOT_ACCEPTABLE" | "407 PROXY_AUTHENTICATION_REQUIRED" | "408 REQUEST_TIMEOUT" | "409 CONFLICT" | "410 GONE" | "411 LENGTH_REQUIRED" | "412 PRECONDITION_FAILED" | "413 PAYLOAD_TOO_LARGE" | "413 REQUEST_ENTITY_TOO_LARGE" | "414 URI_TOO_LONG" | "414 REQUEST_URI_TOO_LONG" | "415 UNSUPPORTED_MEDIA_TYPE" | "416 REQUESTED_RANGE_NOT_SATISFIABLE" | "417 EXPECTATION_FAILED" | "418 I_AM_A_TEAPOT" | "419 INSUFFICIENT_SPACE_ON_RESOURCE" | "420 METHOD_FAILURE" | "421 DESTINATION_LOCKED" | "422 UNPROCESSABLE_ENTITY" | "423 LOCKED" | "424 FAILED_DEPENDENCY" | "425 TOO_EARLY" | "426 UPGRADE_REQUIRED" | "428 PRECONDITION_REQUIRED" | "429 TOO_MANY_REQUESTS" | "431 REQUEST_HEADER_FIELDS_TOO_LARGE" | "451 UNAVAILABLE_FOR_LEGAL_REASONS" | "500 INTERNAL_SERVER_ERROR" | "501 NOT_IMPLEMENTED" | "502 BAD_GATEWAY" | "503 SERVICE_UNAVAILABLE" | "504 GATEWAY_TIMEOUT" | "505 HTTP_VERSION_NOT_SUPPORTED" | "506 VARIANT_ALSO_NEGOTIATES" | "507 INSUFFICIENT_STORAGE" | "508 LOOP_DETECTED" | "509 BANDWIDTH_LIMIT_EXCEEDED" | "510 NOT_EXTENDED" | "511 NETWORK_AUTHENTICATION_REQUIRED";
        HttpStatusCode: {
            error?: boolean;
            is1xxInformational?: boolean;
            is2xxSuccessful?: boolean;
            is3xxRedirection?: boolean;
            is4xxClientError?: boolean;
            is5xxServerError?: boolean;
        };
        JspConfigDescriptor: {
            taglibs?: components["schemas"]["TaglibDescriptor"][];
            jspPropertyGroups?: components["schemas"]["JspPropertyGroupDescriptor"][];
        };
        JspPropertyGroupDescriptor: {
            buffer?: string;
            elIgnored?: string;
            errorOnELNotFound?: string;
            pageEncoding?: string;
            scriptingInvalid?: string;
            isXml?: string;
            includePreludes?: string[];
            includeCodas?: string[];
            deferredSyntaxAllowedAsLiteral?: string;
            trimDirectiveWhitespaces?: string;
            errorOnUndeclaredNamespace?: string;
            defaultContentType?: string;
            urlPatterns?: string[];
        };
        RedirectView: {
            applicationContext?: components["schemas"]["ApplicationContext"];
            servletContext?: components["schemas"]["ServletContext"];
            contentType?: string;
            requestContextAttribute?: string;
            staticAttributes?: {
                [key: string]: unknown;
            };
            exposePathVariables?: boolean;
            exposeContextBeansAsAttributes?: boolean;
            exposedContextBeanNames?: string[];
            beanName?: string;
            url?: string;
            contextRelative?: boolean;
            http10Compatible?: boolean;
            exposeModelAttributes?: boolean;
            encodingScheme?: string;
            statusCode?: components["schemas"]["DefaultHttpStatusCode"] | components["schemas"]["HttpStatus"];
            expandUriTemplateVariables?: boolean;
            propagateQueryParams?: boolean;
            hosts?: string[];
            redirectView?: boolean;
            propagateQueryProperties?: boolean;
            attributesMap?: {
                [key: string]: unknown;
            };
            attributes?: {
                [key: string]: string;
            };
            attributesCSV?: string;
        };
        ServletContext: {
            classLoader?: {
                name?: string;
                registeredAsParallelCapable?: boolean;
                definedPackages?: {
                    name?: string;
                    annotations?: unknown[];
                    declaredAnnotations?: unknown[];
                    sealed?: boolean;
                    specificationTitle?: string;
                    specificationVersion?: string;
                    specificationVendor?: string;
                    implementationTitle?: string;
                    implementationVersion?: string;
                    implementationVendor?: string;
                }[];
                defaultAssertionStatus?: boolean;
            };
            /** Format: int32 */
            majorVersion?: number;
            /** Format: int32 */
            minorVersion?: number;
            sessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
            sessionCookieConfig?: components["schemas"]["SessionCookieConfig"];
            virtualServerName?: string;
            attributeNames?: unknown;
            /** Format: int32 */
            sessionTimeout?: number;
            contextPath?: string;
            initParameterNames?: unknown;
            servletRegistrations?: {
                [key: string]: components["schemas"]["ServletRegistration"];
            };
            /** Format: int32 */
            effectiveMajorVersion?: number;
            /** Format: int32 */
            effectiveMinorVersion?: number;
            serverInfo?: string;
            servletContextName?: string;
            filterRegistrations?: {
                [key: string]: components["schemas"]["FilterRegistration"];
            };
            defaultSessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
            effectiveSessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
            jspConfigDescriptor?: components["schemas"]["JspConfigDescriptor"];
            requestCharacterEncoding?: string;
            responseCharacterEncoding?: string;
        };
        ServletRegistration: {
            runAsRole?: string;
            mappings?: string[];
            name?: string;
            className?: string;
            initParameters?: {
                [key: string]: string;
            };
        };
        SessionCookieConfig: {
            name?: string;
            path?: string;
            attributes?: {
                [key: string]: string;
            };
            /** @deprecated */
            comment?: string;
            /** Format: int32 */
            maxAge?: number;
            domain?: string;
            httpOnly?: boolean;
            secure?: boolean;
        };
        TaglibDescriptor: {
            taglibURI?: string;
            taglibLocation?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Notification"][];
                };
            };
        };
    };
    updateNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Notification"];
                };
            };
        };
    };
    createNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Notification"];
                };
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InventoryTransaction"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryTransaction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InventoryTransaction"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query: {
                ingredient: components["schemas"]["IngredientUpdateRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    save: {
        parameters: {
            query: {
                ingredient: components["schemas"]["IngredientCreateRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    getAllIngredientCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientCategory"][];
                };
            };
        };
    };
    updateIngredientCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCategory"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientCategory"];
                };
            };
        };
    };
    createIngredientCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCategory"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientCategory"];
                };
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["DishCategory"][];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["DishCategory"];
                };
            };
        };
    };
    save_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCategoryCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["DishCategory"];
                };
            };
        };
    };
    findAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Discount"][];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscountUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Discount"];
                };
            };
        };
    };
    save_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscountCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Discount"];
                };
            };
        };
    };
    findAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Account"][];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Account"];
                };
            };
        };
    };
    save_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Account"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query: {
                otp: string;
                email: string;
                newPassword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MakeOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyOtp: {
        parameters: {
            query: {
                email: string;
                otp: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": string;
                };
            };
        };
    };
    findAll_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["InventoryTransaction"][];
                };
            };
        };
    };
    save_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryTransaction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["InventoryTransaction"];
                };
            };
        };
    };
    save_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": components["schemas"]["Dish"];
                };
            };
        };
    };
    findAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishTemplate"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishTemplate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishTemplate"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Account"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Account"];
                };
            };
        };
    };
    markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    demo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WarpResponseUserDTO"];
                };
            };
        };
    };
    deleteRecipe: {
        parameters: {
            query: {
                DishId: number;
                IngredientId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "_/_": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RedirectView"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    handleVnPayReturn: {
        parameters: {
            query: {
                params: {
                    [key: string]: string;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    testPayment: {
        parameters: {
            query: {
                paymentMethodName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    handleMomoReturn: {
        parameters: {
            query: {
                params: {
                    [key: string]: string;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getNotificationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Notification"];
                };
            };
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNotificationByAccountId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Notification"][];
                };
            };
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    findByName: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    findById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IngredientCategory"];
                };
            };
        };
    };
    deleteIngredientCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findBySizeCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sizeCode: "S" | "M" | "L";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishTemplate"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sizeCode: "S" | "M" | "L";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishCategory"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    findById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Discount"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    findById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Account"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
